name: smqf
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python==3.11.0
  - attrs
  - joblib
  - numpy
  - matplotlib
  - numba
  - pandas
  - pyodbc
  - conda-forge::gplearn
  - conda-forge::scikit-learn
  - conda-forge::xgboost
  - jupyterlab
prefix: /opt/miniconda3/envs/smqf
